### ISSUE TITLE
 warning: ISO C forbids nested functions

### ISSUE THREAD

**Issue by SG7** [EmbedJournal/c-utils#5]
The project was compiled with gcc 4.84.

 gcc prog.c -Wall -Wextra -std=c99 -pedantic

Multiple warnings occurred:

```
 warning: ISO C forbids nested functions [-Wpedantic]
     inline int x##_push_refd(t * pt)           \
     ^
 warning: ISO C forbids nested functions [-Wpedantic]
     inline int x##_pop_refd(t * pt)            \

 warning: ISO C forbids nested functions [-Wpedantic]
     inline int x##_peek_refd(t * pt)           \
     ^
 warning: ISO C forbids nested functions [-Wpedantic]
     inline int x##_push_refd(t * pt)           \
     ^	 
```
Can we avoid nesting?

**Comment by cbsiddharth** [comment]
I suppose you are trying to use `CIRC_BUF_DEF` within functions. Please read my response to your issue #2.

**Comment by SG7** [comment]
From my tests the `CIRC_BUF_DEF` can be used within functions without any problems or compiler warnings! The pointer to the buffer can be also passed around. 

Strangely enough, I am not able to reproduce the above warnings anymore.
