### ISSUE TITLE
Purpose of  zero_pad(tail, circ_buf->element_size);

### ISSUE THREAD

**Issue by SG7** [EmbedJournal/c-utils#6]
The function:

`int circ_gbuf_pop(circ_gbuf_t *circ_buf, void *elem, int read_only)`

contains call to:

`zero_pad(tail, circ_buf->element_size);`

I am not sure if this function is needed. For speed improvement it could be removed.  Am I wrong?

**Comment by SG7** [comment]
The lines:

```
        *tail = 0;
        zero_pad(tail, circ_buf->element_size);  
```
are suppose to do a "cleanup" after the element was removed from the buffer.

Unfortunately, that is done in very inefficient way.

Because of `*tail=0;` the function:

` strnlen(s,len);` 

 treats `tail` as an empty zero terminated string and will always return `0` forcing `zero_pad` function to go via all `elem` bytes

```
    for(i=0; i<len; i++)
        s[i] = 0;
```

It is better to replace: 

```
        *tail = 0;
        zero_pad(tail, circ_buf->element_size);  
```
with faster one line of code
`        memset(tail, 0, circ_buf->element_size); `

which will do exactly the same. 

Alternatively, there is nothing wrong with leaving the trace of popped element in the buffer, speeding up the pop operation. In this case there is no need to have that cleanup.

Cleanup can be left to the conditional compilation:

```
#if ZERO_PAD
        memset(tail, 0, circ_buf->element_size);
#endif

```

**Comment by cbsiddharth** [comment]
Agreed. Fixed.
